name: Build Supabase Auth Image with Patch

on:
  push:
    branches:
      - "v2.154.2-patch"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_OBEYED_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_OBEYED_ACCESS_TOKEN }}

      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jabbrai/supabase-auth:${{ github.ref_name }}

